"""empty message

Revision ID: fce79bacb815
Revises: 721816a827bc
Create Date: 2022-06-03 14:37:52.215126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce79bacb815'
down_revision = '721816a827bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise', sa.String(length=120), nullable=False),
    sa.Column('sets', sa.String(length=80), nullable=False),
    sa.Column('reps', sa.String(length=80), nullable=False),
    sa.Column('weight_used', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exercise')
    )
    op.drop_table('workoutA')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workoutA',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"workoutA_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('squat', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('bench', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('chinup', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='workoutA_pkey'),
    sa.UniqueConstraint('squat', name='workoutA_squat_key')
    )
    op.drop_table('workout_table')
    # ### end Alembic commands ###
